# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
    exclude_types:
      - binary
    exclude: \.img$
  - id: end-of-file-fixer
    exclude_types:
      - binary
    exclude: \.img$
  - id: check-yaml
- repo: local
  hooks:
    - id: pep8
      verbose: true
      name: pep8
      entry: env PATH=.tox/style/bin python tools/cpep8.py
      files: \.py$
      language: python
