#!/usr/bin/python
#
# Copyright 2008 Dan Smith <dsmith@danplanet.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from chirp import platform, CHIRP_VERSION

# Hack to setup environment
platform.get_platform()

import gtk
import sys
import os

from chirpui import mainapp, config

if hasattr(sys, "frozen"):
    log = file("debug.log", "w", 0)
    sys.stderr = log
    sys.stdout = log
elif not os.isatty(0):
    log = file(platform.get_platform().config_file("debug.log"), "w", 0)
    sys.stdout = log
    sys.stderr = log

print "CHIRP %s on %s" % (CHIRP_VERSION, platform.get_platform().os_version_string())

a = mainapp.ChirpMain()

profile = False
if len(sys.argv) > 1:
    arg = sys.argv[1]
    index = 2
    if arg == "--profile":
        profile = True
    elif arg == "--help":
        print "Usage: %s [file...]" % sys.argv[0]
        sys.exit(0)
    else:
        index = 1
else:
    index = 1

for i in sys.argv[index:]:
    print "Opening %s" % i
    a.do_open(i)

a.show()

if profile:
    import cProfile, pstats
    cProfile.run("gtk.main()", "chirpw.stats")
    p = pstats.Stats("chirpw.stats")
    p.sort_stats("cumulative").print_stats(10)
else:
    gtk.main()

if config._CONFIG:
    config._CONFIG.set("last_dir",
                       platform.get_platform().get_last_dir(),
                       "state")
    config._CONFIG.save()
