name: Tests
on:
  pull_request:
  push:
jobs:
  style:
    name: Style checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tox
        uses: ./.github/actions/py2-tox
        with:
          tox_target: style

  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tox
        uses: ./.github/actions/py2-tox
        with:
          tox_target: unit

  driver:
    name: Driver tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tox
        uses: ./.github/actions/py2-tox
        with:
          tox_target: driver

  matrix:
    name: Create support matrix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tox
        uses: ./.github/actions/py2-tox
        with:
          tox_target: makesupported
      - name: Archive support matrix
        uses: actions/upload-artifact@v3
        with:
          name: support-matrix
          path: model_support.html
