name: Tests
on:
  pull_request:
jobs:
  style:
    name: Style checks
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tox
        uses: ./.github/actions/py3-tox
        with:
          tox_target: style

  unit:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tox
        uses: ./.github/actions/py3-tox
        with:
          tox_target: unit
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: unit_report
          path: unit_report.html

  driver:
    name: Driver tests (Python 3.8)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tox
        uses: ./.github/actions/py3-tox
        with:
          tox_target: fast-driver
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: driver_report
          path: driver_report.html

  driver-py:
    name: Driver tests (Python 3.10)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tox
        uses: ./.github/actions/py3-tox
        with:
          tox_target: fast-driver

  matrix:
    name: Create support matrix
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tox
        uses: ./.github/actions/py3-tox
        with:
          tox_target: makesupported
      - name: Archive support matrix
        uses: actions/upload-artifact@v3
        with:
          name: support-matrix
          path: model_support.html
