name: report
on:
  workflow_run:
    workflows: [Tests]
    types: [completed]

permissions:
  checks: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Download test report
        uses: dawidd6/action-download-artifact@v2
        with:
          name: unit_results
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Publish report
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          report_paths: '*.xml'
          
